
//Rest Client
//allID
GET http://localhost:13000/users

######
//byID
GET http://localhost:13000/users/6364cbadbd4aee987d8fed92

####
// also createn funktioniert aber suchen noch nicht
POST http://localhost:13000/users
Content-Type: application/json

{
    "username": "testdft",
    "password": "jasmin12"
}


###
DELETE http://localhost:13000/users/635e9ec81dcd1606048d4c3e


###

PATCH http://localhost:13000/users/635ea0a66690180a2a9ea2be
Content-Type: application/json

{
    "username": "Timbooooo"
}

###

POST http://localhost:13000/users/login
Content-Type: application/json

{
    "username": "jan",
    "password": "jasmin12"
}

###
//get all task
GET http://localhost:13000/tasks


###
//create task

POST http://localhost:13000/tasks
Content-Type: application/json

{
    "title": "Jan",
    "text": "jasmin12",
    "done": 0,
    "user_id": "635f989f83a8d9ef9c071691"
}

### delete task
DELETE http://localhost:13000/tasks/6364e0f2ee9d89f3cb89fa2a
